/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class  LibraryTest {
    @Test public void rollTest() {
        int num = 5;
        long[] rollArray = Library.roll(num);
        long expected = num;
        long actual = rollArray.length;
        assertEquals(expected, actual);
    }

    @Test public void duplicateTest() {
        int[] nums = {1, 2, 3, 5};
        boolean result = Library.containsDuplicates(nums);
        assertFalse("The test passes if the array has no duplicate", result);
    }
    @Test public void duplicateTest2() {
        int[] numbs = {1, 2, 3, 3, 5};
        boolean result = Library.containsDuplicates(numbs);
        assertTrue("The test passes if the array has duplicate", result);
    }

    @Test public void averageTest() {
        double expected = 2.8;
        int[] nums = {1, 2, 3, 3, 5};
        double actual = Library.calculatedAverage(nums);
        assertEquals(expected,actual,0);
    }

    @Test public void lowestAverageTest() {
        double expected = 57.0;
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        double actual = Library.lowestAverage(weeklyMonthTemperatures);
        assertEquals(expected,actual,0);
    }
}



