/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;


import java.lang.*;
import java.util.*;

public class Library {
    public static long[] roll(int num) {
        int[] numArray = {1, 2, 3, 4};
        System.out.println(num);
        long[] randomRollArray = new long[num];


        for (int i = 0; i < num; i++) {
            double randomNumber = (1 + Math.random() * 6);
            long ranNum = Math.round(Math.floor(randomNumber));
            randomRollArray[i] = ranNum;
            System.out.println(ranNum);
        }
        return randomRollArray;
    }

    public static boolean containsDuplicates(int[] nums) {
        for (int i = 0; i < nums.length; i++) {
            for (int j = i + 1; j < nums.length; j++) {
                if (nums[i] == nums[j]) {
                    System.out.println(nums[i]);
                    System.out.println("Theres a match");
                    return true;
                }
            }
        }
        System.out.println("not a match");
        return false;

    }

    public static double calculatedAverage(int[] nums) {
        double total = 0;
        for (int i = 0; i < nums.length; i++) {
            total = +total + nums[i];

        }
//        System.out.println(total);
        double average = total / nums.length;
//        System.out.println(average);
        return average;
    }

    public static double lowestAverage(int[][] arrayOfArrays) {
        double lowestAvg = 1000;
        for (int i = 0; i < arrayOfArrays.length; i++) {
            double tempAvg = calculatedAverage(arrayOfArrays[i]);
            System.out.println("this is the average " + tempAvg);
            if (tempAvg < lowestAvg) {
                lowestAvg = tempAvg;
            }
            System.out.println("this is the lowest average " + lowestAvg);
        }
        return lowestAvg;
    }


    public static String analyzeWeatherData(int[][]arr){
        Set<Integer> distinctNumbers = new HashSet<>();
        ArrayList<Integer>newNumbers = new ArrayList<>();
        for(int[]testArr : arr) {
            for (int number : testArr) {
                newNumbers.add(number);
            }
        }
        distinctNumbers.addAll(newNumbers);

        System.out.println("this is the test weather data"
                + distinctNumbers);
        int lowNumber = 100;
        int highNumber = 0;
        for(int num : distinctNumbers){
            if(lowNumber > num){
                lowNumber = num;
            }else if(highNumber < num){
                highNumber = num;
            }
        }
        StringBuilder results = new StringBuilder("High: "
                + highNumber + "\nLow: " + lowNumber + "\n");
        for(int i = lowNumber; i <= highNumber; i++){
                if (!distinctNumbers.contains(i)){
                    System.out.println("this number is not there " + i);
                    results.append("Never saw temperature: " + i + "\n");
                }
            }
        System.out.println(results.toString());
        String resultsString = results.toString();

        return resultsString;
    }

    public static String tallyElection(List<String> list){
        Set<String> distinctElements = new HashSet<>();
        distinctElements.addAll(list);
        HashMap<String, Integer>votesForEach = new HashMap<>();
        for(String element : distinctElements){
            votesForEach.put(element,0 );
        }
        int mostVotes = 0;
        String winner = "";
        for(String element : list){
            int counter = votesForEach.get(element);
            counter++;
            votesForEach.put(element, counter);
            if(counter > mostVotes){
                mostVotes = counter;
                winner = element;

            }
        }
        System.out.println(winner + " received the most votes!");
        System.out.println(mostVotes);
        System.out.println(votesForEach.values());
        System.out.println(list);
        System.out.println(distinctElements);
        System.out.println(votesForEach);


        return winner + " received the most votes!";
    }

}



