/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;


import java.lang.*;


public class Library {
    public static long[] roll(int num) {
        int[] numArray = {1, 2, 3, 4};
        System.out.println(num);
        long[] randomRollArray = new long[num];


        for (int i = 0; i < num; i++) {
            double randomNumber = (1 + Math.random() * 6);
            long ranNum = Math.round(Math.floor(randomNumber));
            randomRollArray[i] = ranNum;
            System.out.println(ranNum);
        }
        return randomRollArray;
    }

    public static boolean containsDuplicates(int[] nums) {
        for (int i = 0; i < nums.length; i++) {
            for (int j = i + 1; j < nums.length; j++) {
                if (nums[i] == nums[j]) {
                    System.out.println(nums[i]);
                    System.out.println("Theres a match");
                    return true;
                }
            }
        }
        System.out.println("not a match");
        return false;

    }

    public static double calculatedAverage(int[] nums) {
        double total = 0;
        for (int i = 0; i < nums.length; i++) {
            total = +total + nums[i];

        }
//        System.out.println(total);
        double average = total / nums.length;
//        System.out.println(average);
        return average;
    }

    public static double lowestAverage(int[][] arrayOfArrays) {
        double lowestAvg = 1000;
        for (int i = 0; i < arrayOfArrays.length; i++) {
            double tempAvg = calculatedAverage(arrayOfArrays[i]);
            System.out.println("this is the average " + tempAvg);
            if (tempAvg < lowestAvg) {
                lowestAvg = tempAvg;
            }
            System.out.println("this is the lowest average " + lowestAvg);
        }
        return lowestAvg;
    }
}



