/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {

        assertNotNull("app should have a greeting", App.getGreeting());
    }
    @Test public void mainTest(){
        int testNumber = 46;
        int actual = App.readfile("src/test/resources/gates.js");
        assertEquals("Must be equal", testNumber, actual );

        testNumber = 1;
        actual = App.readfile("src/test/resources/test.js");
        assertEquals("Must be equal", testNumber, actual );

        testNumber = 0;
        actual = App.readfile("src/test/resources/test2.js");
        assertEquals("Must be equal", testNumber, actual );

        testNumber = 10;
        actual = App.readfile("src/test/resources/test3.js");
        assertEquals("Must be equal", testNumber, actual );

        testNumber = 0;
        actual = App.readfile("src/test/resources/test4.js");
        assertEquals("Must be equal", testNumber, actual );


    }

}
